name: Label Issues
on:
  issues:
    types:
      - opened
      - reopened
      - edited
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Renato66/auto-label@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        configuration-path: '.github/auto-label.json'
          